name: invest_track
description: A Fintech dashboard application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Backend & Auth
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1

  # State Management
  provider: ^6.1.1

  # UI & Assets
  google_fonts: ^7.0.2
  google_nav_bar: ^5.0.6
  fl_chart: ^1.1.1
  intl: ^0.20.2

  # API & AI
  http: ^1.2.0
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env